### ISSUE TITLE
Update list of UTMs and other Google parameters that should be preserved

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [CardinalPath/gtm-template-ga-queryparam-stripper#1]
Hi

I would suggest to include those

utm_referrer,utm_nooverride,utm_source,utm_campaign,utm_medium,utm_term,utm_content,utm_id,gclid,dclid,gclsrc,gbraid,wbraid,utm_source_platform,utm_creative_format,utm_marketing_tactic,srsltid

**Comment by btripple** [comment]
Thanks, I will ad most of these.  utm_referrer & utm_nooverride may not be needed.

**Comment by googleanalyticsresoneo** [comment]
I believe it's better to add utm_referrer & utm_nooverride too instead of taking the risk of breaking something by dropping them
